swagger: "2.0"
info: 
  description: Swagger doc for /api/server4/config  
  title: Swagger doc for /api/server4/config  
  version: 1.0.0
paths: 
  /api/server4/config: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              Information: 
                type: object
                additionalProperties: true
                properties: 
                  slot4_sensor_health: 
                    type: string
                  slot4_trigger_hpr: 
                    type: string
                  slot4_cpu_ppin: 
                    type: string
                  sysfw_ver_slot4: 
                    type: string
                  slot4_boot_order: 
                    type: string
                  slot4_por_cfg: 
                    type: string
                  pwr_server4_last_state: 
                    type: string
                  slot4_sel_error: 
                    type: string
                  identify_slot4: 
                    type: string
              Resources: 
                type: array
                items: 
                  type: string
              Actions: 
                type: array
                items: 
                  type: string
            
